plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

env: production

# Site settings
timezone: US/Pacific

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tobiasduerschmid.github.io/" # the base hostname & protocol for your site

title: ArchesLab
author: Tobias DÃ¼rschmid

languages: [ 'en' ]

description: > # theis means to ignore newlines until "baseurl:"
    UCLA ArchesLab  - Architectures of Evolving Software Lab.
subheading: > # this means to ignore newlines until "baseurl:"
    We are a research lab at UCLA focused on the design and implementation of software architectures.

defaults:
  - scope:
      path: ''
    values:
      lang: en
  - scope:
      path: 'en'
    values:
      lang: en

# Handling Reading
safe: true
encoding: utf-8

# Build settings
markdown: kramdown

html_press:
  unquoted_attributes: false
  drop_empty_values: false
  strip_crlf: false
  js_minifier_options: false
